---
- name: Playbook for test
  hosts: web
  vars:
    env: test
    remote_role: app # define server role
  become: yes #sudo権限でコマンドを実行できる
  vars_files:
    - vars/common.yml
    - vars/test.yml
  gather_facts: false
  roles:
    - env
    - git
    - ruby
    - nginx
    - mysql
    - unicorn
